[package]
name = "turbo"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[features]
# By default, we enable native-tls for reqwest via downstream transitive features.
# This is for the convenience of running daily dev workflows, i.e running
# `cargo xxx` without explicitly specifying features, not that we want to
# promote this as default backend.
default = ["native-tls"]
native-tls = ["turborepo-lib/native-tls"]
rustls-tls = ["turborepo-lib/rustls-tls"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
build-target = "0.4.0"

[dev-dependencies]
assert_cmd = "2.0.7"
itertools = "0.10.5"
pretty_assertions = "1.3.0"

[dependencies]
anyhow = { version = "1.0.65", features = ["backtrace"] }
clap = { version = "4.0.22", features = ["derive"] }
clap_complete = "4.0.6"
dunce = "1.0"
log = "0.4.17"
predicates = "2.1.1"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
serde_yaml = "0.8.26"
tiny-gradient = "0.1"
turborepo-lib = { path = "../turborepo-lib" }
