[package]
name = "turbo"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[features]
# By default, we enable native-tls for reqwest via downstream transitive features.
# This is for the convenience of running daily dev workflows, i.e running
# `cargo xxx` without explicitly specifying features, not that we want to
# promote this as default backend.
default = ["native-tls"]
native-tls = ["turborepo-lib/native-tls"]
rustls-tls = ["turborepo-lib/rustls-tls"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
build-target = "0.4.0"

[dev-dependencies]
assert_cmd = { workspace = true }
itertools = { workspace = true }
pretty_assertions = { workspace = true }

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
clap = { workspace = true, features = ["derive"] }
clap_complete = { workspace = true }
ctrlc = { version = "3.2.5", features = ["termination"] }
dunce = { workspace = true }
log = { workspace = true }
predicates = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
shared_child = "1.0.0"
tiny-gradient = { workspace = true }
turborepo-lib = { workspace = true }
