[workspace]
resolver = "2"

members = [
  "crates/auto-hash-map",
  "crates/vc-test",
  "crates/turbo-malloc",
  "crates/turbo-tasks-build",
  "crates/turbo-tasks-hash",
  "crates/turbo-tasks-macros-shared",
  "crates/turbo-tasks-testing",
  "crates/turbo-tasks",
  "crates/turbo-tasks-macros",
  "crates/turbo-tasks-memory",
  "xtask",
]

default-members = [
  "crates/auto-hash-map",
  "crates/vc-test",
  "crates/turbo-malloc",
  "crates/turbo-tasks-build",
  "crates/turbo-tasks-hash",
  "crates/turbo-tasks-macros-shared",
  "crates/turbo-tasks-testing",
  "crates/turbo-tasks",
  "crates/turbo-tasks-macros",
  "crates/turbo-tasks-memory",
  "xtask",
]

[profile.dev.package.turbo-tasks-macros]
opt-level = 3

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 3

# Declare dependencies used across workspace packages requires single version bump.
# ref: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace
[workspace.dependencies]
indexmap = { version = "1.9.2" }
indoc = "1.0"
# Keep consistent with preset_env_base through swc_core
browserslist-rs = { version = "0.12.2" }
swc_core = { version = "0.59.26" }
testing = { version = "0.31.31" }
swc_emotion = { version = "0.29.4" }
styled_jsx = { version = "0.30.4" }
styled_components = { version = "0.53.4" }
modularize_imports = { version = "0.26.4" }
mdxjs = { version = "0.1.6" }
next-dev = { path = "crates/next-dev", version = "0.1.0" }
node-file-trace = { path = "crates/node-file-trace", version = "0.1.0" }
# Be careful when selecting tls backend, including change default tls backend.
# If you changed, must verify with ALL build targets with next-swc to ensure
# it works. next-swc have various platforms, some doesn't support native (using openssl-sys)
# and some aren't buildable with rustls.
reqwest = { version = "0.11.13", default-features = false }
async-compression = { version = "0.3.13", default-features = false, features = [
  "gzip",
  "tokio",
] }
tokio-util = { version = "0.7.7", features = ["io"] }
