[workspace]
resolver = "2"

members = [
  "crates/auto-hash-map",
  "crates/next-binding",
  "crates/next-core",
  "crates/next-dev",
  "crates/next-transform-dynamic",
  "crates/next-transform-strip-page-exports",
  "crates/node-file-trace",
  "crates/swc-ast-explorer",
  "crates/turbo-malloc",
  "crates/turbo-tasks-build",
  "crates/turbo-tasks-env",
  "crates/turbo-tasks-fetch",
  "crates/turbo-tasks-fs",
  "crates/turbo-tasks-hash",
  "crates/turbo-tasks-macros",
  "crates/turbo-tasks-macros-shared",
  "crates/turbo-tasks-memory",
  "crates/turbo-tasks-testing",
  "crates/turbo-tasks",
  "crates/turbopack-cli-utils",
  "crates/turbopack-core",
  "crates/turbopack-create-test-app",
  "crates/turbopack-css",
  "crates/turbopack-dev-server",
  "crates/turbopack-ecmascript",
  "crates/turbopack-env",
  "crates/turbopack-mdx",
  "crates/turbopack-node",
  "crates/turbopack-json",
  "crates/turbopack-static",
  "crates/turbopack-swc-utils",
  "crates/turbopack",
  "crates/turbopack-tests",
  "crates/turborepo",
  "crates/turborepo-lib",
  "crates/turbo-updater",
  "xtask",
]

default-members = [
  "crates/auto-hash-map",
  "crates/next-binding",
  "crates/next-core",
  "crates/next-dev",
  "crates/next-transform-dynamic",
  "crates/next-transform-strip-page-exports",
  "crates/node-file-trace",
  "crates/swc-ast-explorer",
  "crates/turbo-malloc",
  "crates/turbo-tasks-build",
  "crates/turbo-tasks-env",
  "crates/turbo-tasks-fs",
  "crates/turbo-tasks-hash",
  "crates/turbo-tasks-macros",
  "crates/turbo-tasks-macros-shared",
  "crates/turbo-tasks-memory",
  "crates/turbo-tasks-testing",
  "crates/turbo-tasks",
  "crates/turbopack-cli-utils",
  "crates/turbopack-core",
  "crates/turbopack-create-test-app",
  "crates/turbopack-css",
  "crates/turbopack-dev-server",
  "crates/turbopack-ecmascript",
  "crates/turbopack-env",
  "crates/turbopack-json",
  "crates/turbopack-static",
  "crates/turbopack-swc-utils",
  "crates/turbopack",
  "crates/turbopack-tests",
  "xtask",
]

[profile.release]

[profile.bench]

[profile.dev.package.turbo-tasks-macros]
opt-level = 3

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 3

# Declare dependencies used across workspace packages requires single version bump.
# ref: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace
[workspace.dependencies]
indexmap = { version = "1.9.2" }
# Keep consistent with preset_env_base through swc_core
browserslist-rs = { version = "0.12.2" }
swc_core = { version = "0.53.0" }
testing = { version = "0.31.25" }
swc_emotion = { version = "0.28.9" }
styled_jsx = { version = "0.29.13" }
styled_components = { version = "0.52.13" }
modularize_imports = { version = "0.25.13" }
mdxjs = { version = "0.1.4" }
next-dev = { path = "crates/next-dev", version = "0.1.0" }
node-file-trace = { path = "crates/node-file-trace", version = "0.1.0" }
# Be careful when selecting tls backend, including change default tls backend.
# If you changed, must verify with ALL build targets with next-swc to ensure
# it works. next-swc have various platforms, some doesn't support native (using openssl-sys)
# and some aren't buildable with rustls.
reqwest = { version = "0.11.13", default-features = false }
