[workspace]
resolver = "2"

members = [
  "crates/next-binding",
  "crates/next-core",
  "crates/next-dev",
  "crates/node-file-trace",
  "crates/swc-ast-explorer",
  "crates/turbo-malloc",
  "crates/turbo-tasks-build",
  "crates/turbo-tasks-env",
  "crates/turbo-tasks-fs",
  "crates/turbo-tasks-hash",
  "crates/turbo-tasks-macros",
  "crates/turbo-tasks-macros-shared",
  "crates/turbo-tasks-memory",
  "crates/turbo-tasks-testing",
  "crates/turbo-tasks",
  "crates/turbopack-cli-utils",
  "crates/turbopack-core",
  "crates/turbopack-create-test-app",
  "crates/turbopack-css",
  "crates/turbopack-dev-server",
  "crates/turbopack-ecmascript",
  "crates/turbopack-env",
  "crates/turbopack-json",
  "crates/turbopack-static",
  "crates/turbopack-swc-utils",
  "crates/turbopack",
  "crates/turbopack-tests",
  "shim",
  "xtask",
]

default-members = [
  "crates/next-core",
  "crates/next-dev",
  "crates/node-file-trace",
  "crates/swc-ast-explorer",
  "crates/turbo-malloc",
  "crates/turbo-tasks-build",
  "crates/turbo-tasks-env",
  "crates/turbo-tasks-fs",
  "crates/turbo-tasks-hash",
  "crates/turbo-tasks-macros",
  "crates/turbo-tasks-macros-shared",
  "crates/turbo-tasks-memory",
  "crates/turbo-tasks-testing",
  "crates/turbo-tasks",
  "crates/turbopack-cli-utils",
  "crates/turbopack-core",
  "crates/turbopack-create-test-app",
  "crates/turbopack-css",
  "crates/turbopack-dev-server",
  "crates/turbopack-ecmascript",
  "crates/turbopack-env",
  "crates/turbopack-json",
  "crates/turbopack-static",
  "crates/turbopack-swc-utils",
  "crates/turbopack",
  "crates/turbopack-tests",
  "xtask",
]

[profile.release]

[profile.bench]

[profile.dev.package.turbo-tasks-macros]
opt-level = 3

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 3

# Declare dependencies used across workspace packages requires single version bump.
# ref: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace
[workspace.dependencies]
# This version pin is workaround for https://github.com/tkaitchuck/aHash/issues/95
indexmap = { version = "=1.6.2" }
swc_core = { version = "0.43.23" }
testing = {version = "0.31.14"}
swc_emotion = { version = "0.28.1" }
styled_jsx = { version = "0.29.1" }
styled_components = { version = "0.52.1" }
modularize_imports = { version = "0.25.5" }
mdxjs = { version = "0.1.1" }
next-dev = { path = "crates/next-dev", version = "0.1.0" }
node-file-trace = { path = "crates/node-file-trace", version = "0.1.0" }