[package]
name = "turborepo-scm"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dunce = { workspace = true }
git2 = { version = "0.16.1", default-features = false }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
