project_name: turbo
before:
  hooks:
    - make compile-protos
    - go mod tidy
builds:
  - id: turbo
    main: ./cmd/turbo
    binary: bin/turbo
    hooks:
      pre:
        - cmd: ./scripts/npm-native-packages/npm-native-packages.js {{ .Os }} {{ .Arch }} {{ .Version }}
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=1
    targets:
      - linux_arm64
      - linux_amd64
      - darwin_arm64
      - darwin_amd64
      - windows_arm64
      - windows_amd64
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
      - goos: linux
        goarch: amd64
        goamd64: v1
        env:
          - CC=x86_64-linux-gnu-gcc
          - CXX=x86_64-linux-gnu-g++
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang
          - CXX=oa64-clang++
      - goos: darwin
        goarch: amd64
        goamd64: v1
        env:
          - CC=o64-clang
          - CXX=o64-clang++
      - goos: windows
        goarch: arm64
        env:
          - CC=/llvm-mingw/llvm-mingw/bin/aarch64-w64-mingw32-gcc
          - CXX=/llvm-mingw/llvm-mingw/bin/aarch64-w64-mingw32-g++
      - goos: windows
        goarch: amd64
        goamd64: v1
        env:
          - CC=x86_64-w64-mingw32-gcc
          - CXX=x86_64-w64-mingw32-g++
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}"
archives:
  - id: github
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    replacements:
      amd64: 64
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
  - id: npm
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    replacements:
      amd64: 64
    format: tar.gz
    files:
      - LICENSE
      - src: "scripts/npm-native-packages/build/{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}/package.json"
        dst: "workaround/.."
        strip_parent: true
      - src: "scripts/npm-native-packages/build/{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}/README.md"
        dst: "workaround/.."
        strip_parent: true
      - src: "scripts/npm-native-packages/build/{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}/bin/*"
        dst: "bin/"
        strip_parent: true
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: vercel
    name: turborepo
  ids:
    - github
  prerelease: auto
  disable: true
publishers:
  - name: npm
    ids:
      - npm
    cmd: "npm publish{{ if .Prerelease }} --tag canary{{ end }} {{ abs .ArtifactPath }}"
