[package]
name = "vercel-api-mock"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
axum-server = "0.4.7"
port_scanner = { workspace = true }
tokio = { workspace = true, features = ["full"] }
turborepo-api-client = { workspace = true }
