[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"

[alias]
xtask = "run --package xtask --"
tr-build = "build -p turbo"
tr-run = "run -p turbo"
tr-test = "test -p turborepo-* -p turbopath -p vercel-api-mock -p turborepo-cache --features rustls-tls"
tr-check = "check -p turbo -p vercel-api-mock -p turborepo-ffi"
# Builds all test code to check for compiler errors before running
tp-pre-test = "nextest run --no-run --release -p turbopack* -p turbo-tasks* -p signposter* -p tracing-signposter -p node-file-trace -p auto-hash-map"
tp-test = "nextest run --release --no-fail-fast -p turbopack* -p turbo-tasks* -p signposter* -p tracing-signposter -p node-file-trace -p auto-hash-map"
# --exclude expects --workspace, so there's no easy way to tell cargo to include all turbopack* packages except turbopack-bench
tp-bench = "bench --workspace --exclude turbopack-bench --exclude turborepo* --exclude turbo --exclude vercel-api-mock --exclude turbopath"
tp-bench-pre-test = "test --no-run --benches --release --workspace --exclude turbopack-bench --exclude turborepo* --exclude turbo --exclude vercel-api-mock --exclude turbopath"
tp-bench-test = "test --benches --release --no-fail-fast --workspace --exclude turbopack-bench --exclude turborepo* --exclude turbo --exclude vercel-api-mock --exclude turbopath"
tp-bench-other-pre-test = "test --no-run --benches --release -p turbopack-bench"
tp-bench-other-test = "test --benches --release -p turbopack-bench"

[target.'cfg(all())']
rustflags = ["--cfg", "tokio_unstable", "-Csymbol-mangling-version=v0", "-Aclippy::too_many_arguments"]
