[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"

[alias]
xtask = "run --package xtask --"
tr-build = "build -p turbo"
tr-run = "run -p turbo"
tr-test = "test -p turborepo-lib -p turborepo-scm -p turborepo-lockfiles -p turbopath -p turborepo-api-client -p vercel-api-mock --features rustls-tls"
tr-check = "check -p turbo -p vercel-api-mock"
# Builds all test code to check for compiler errors before running
tp-pre-test = "nextest run --no-run --workspace --release --exclude turbo --exclude turborepo-ffi --exclude turborepo-lib --exclude turborepo-scm --exclude turbopath --exclude turborepo-lockfiles --exclude turborepo-api-client --exclude vercel-api-mock"
tp-test = "nextest run --workspace --release --no-fail-fast --exclude turbo --exclude turborepo-ffi --exclude turborepo-lib --exclude turborepo-scm --exclude turbopath --exclude turborepo-lockfiles --exclude turborepo-api-client --exclude vercel-api-mock"

[target.'cfg(all())']
rustflags = ["--cfg", "tokio_unstable", "-Csymbol-mangling-version=v0", "-Aclippy::too_many_arguments"]
