[package]
name = "turbopath"
version = "0.1.0"
license = "MPL-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
camino = { version = "1.1.4", features = ["serde1"] }
dunce = { workspace = true }
path-clean = "1.0.1"
# TODO: Make this a crate feature
serde = { workspace = true }
thiserror = { workspace = true }
wax = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
