[package]
name = "turborepo-paths"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
allocative = "0.2.0"
anyhow = { workspace = true }
assert_matches = "1.5.0"
common-path = "1.0.0"
compact_str = "0.7.0"
derivative = "2.2.0"
derive_more = "0.99.17"
dunce = { workspace = true }
gazebo = "0.8.1"
itertools = { workspace = true }
memchr = "2.5.0"
ref-cast = "1.0.14"
relative-path = "1.7.3"
serde = { workspace = true }
smallvec = "1.10.0"
tempfile = { workspace = true }
thiserror = { workspace = true }
