[package]
name = "turborepo-ffi"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
directories = "4.0.1"
prost = "0.11.6"
turborepo-scm = { path = "../turborepo-scm" }

[build-dependencies]
cbindgen = "0.24.3"
prost-build = "0.11.6"
