[package]
name = "next-core"
version = "0.1.0"
description = "TBD"
license = "MPL-2.0"
edition = "2021"

[lib]
bench = false

[dependencies]
anyhow = "1.0.47"
auto-hash-map = { path = "../auto-hash-map" }
crossterm = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
indoc = "1.0"
mime = "0.3.16"
num_cpus = "1.13.1"
once_cell = "1.13.0"
qstring = "0.7.2"
serde = "1.0.136"
serde_json = "1.0.85"
turbo-tasks = { path = "../turbo-tasks" }
turbo-tasks-env = { path = "../turbo-tasks-env" }
turbo-tasks-fetch = { path = "../turbo-tasks-fetch" }
turbo-tasks-fs = { path = "../turbo-tasks-fs" }
turbo-tasks-hash = { path = "../turbo-tasks-hash" }
turbopack = { path = "../turbopack" }
turbopack-core = { path = "../turbopack-core" }
turbopack-dev-server = { path = "../turbopack-dev-server" }
turbopack-ecmascript = { path = "../turbopack-ecmascript" }
turbopack-env = { path = "../turbopack-env" }
turbopack-node = { path = "../turbopack-node" }

[build-dependencies]
turbo-tasks-build = { path = "../turbo-tasks-build" }

[features]
next-font-local = []
native-tls = ["turbo-tasks-fetch/native-tls"]
rustls-tls = ["turbo-tasks-fetch/rustls-tls"]
