[package]
name = "turbo-updater"
version = "0.1.0"
edition = "2021"
description = "Minimal wrapper around update-informer to provide npm registry support and consistent UI"
license = "MPL-2.0"
publish = false

[dependencies]
atty = "0.2"
console = "0.15.5"
semver = "1.0"
serde = { version = "1.0.126", features = ["derive"] }
thiserror = "1.0"
update-informer = "0.6.0"
ureq = { version = "2.3.0" }
