name: Large Repo Benchmark

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Release]
    types:
      - completed

jobs:
  build:
    name: Run Benchmarks
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-go
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build
        run: cd cli && make turbo-prod

      - name: Run benchmarks
        run: cd benchmark && pnpm benchmark

      - name: Save to Tinybird
        if: github.ref == 'refs/heads/main'
        run: |
          curl \
            -i \
            -F "ndjson=@./benchmark/tinybird.ndjson" \
            -X POST \
            -H 'Authorization: Bearer ${{ secrets.TINYBIRD_TOKEN }}' \
            'https://api.us-east.tinybird.co/v0/datasources?format=ndjson&name=turbo_benchmarks&mode=append'
