name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: build and test
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.0
        id: go

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.11

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build & Unit Test
        run: pnpm turbo -- run test --scope=cli --color

      - name: Lint
        run: pnpm turbo -- run lint --scope=cli --color

      - name: E2E Tests
        run: |
          cd cli && make e2e

      - name: Benchmark and Smoke Tests
        run: cd cli && make bench/turbo

  build-win:
    name: build and test
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.0
        id: wingo

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.32.11

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: go test
        run: cd cli && go test ./cmd/... ./internal/...

      - name: go vet
        run: cd cli && go vet ./cmd/... ./internal/...

      - name: Build
        run: cd cli && go build ./cmd/turbo/...

      - name: E2E Tests
        run: cd cli && make e2e

      - name: Benchmark and Smoke Tests
        run: cd cli && make bench/turbo

  examples:
    name: run examples
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Install Sponge
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install -y moreutils
          else
            brew install moreutils
          fi

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Go 1
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.0
        id: go

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.11

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Check examples
        shell: bash
        env:
          FORCE_COLOR: true
        run: ./scripts/run-examples.sh
