# Reusable workflow to execute certain version of Next.js integration tests
# with turbopack.
#
# Refer test.yml for how this workflow is being initialized
# - Workflow can specify `inputs.version` to specify which version of next.js to use, otherwise will use latest release version.
name: Turbopack Next.js integration test

on:
  workflow_call:
    inputs:
      # Allow to specify Next.js version to run integration test against.
      # If not specified, will use latest release version including canary.
      version:
        type: string
      # The base of the test results to compare against. If not specified, will try to compare with latest main branch's test results.
      diff_base:
        type: string
        default: "main"
      force_post_to_slack:
        type: boolean

jobs:
  # First, build next-dev and Next.js both to execute across tests.
  setup_nextjs:
    name: Setup Next.js build
    uses: ./.github/workflows/setup-nextjs-build.yml
    with:
      version: ${{ inputs.version }}

  # Actual test scheduling. These jobs mimic the same jobs in Next.js repo,
  # which we do allow some of duplications to make it easier to update if upstream changes.
  # Refer build_test_deploy.yml in the Next.js repo for more details.
  test_dev:
    # This job name is being used in github action to collect test results. Do not change it, or should update
    # ./.github/actions/next-integration-stat to match the new name.
    name: Next.js integration test (Development)
    runs-on: ubuntu-latest
    needs: [setup_nextjs]
    env:
      # Enabling backtrace will makes snapshot tests fail
      RUST_BACKTRACE: 0
      NEXT_TELEMETRY_DISABLED: 1
      # Path to the next-dev binary located in **docker container** image.
      NEXT_DEV_BIN: /work/next-dev
      FAILED_TEST_LIST_PATH: /work/integration-test-data/test-results/main/failed-test-path-list.json
      # Glob pattern to run specific tests with --turbo.
      NEXT_DEV_TEST_GLOB: "*"
      # pnpm version should match to what upstream next.js uses
      PNPM_VERSION: 7.24.3
    strategy:
      matrix:
        node: [16, 18]
        group: [1, 2, 3, 4]

    steps:
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      # This step is quite same as upstream next.js integration execution, but with some differences:
      # Sets `__INTERNAL_CUSTOM_TURBOPACK_BINARY`, `__INTERNAL_NEXT_DEV_TEST_TURBO_GLOB_MATCH` to setup custom turbopack.
      # Sets `NEXT_TEST_SKIP_RETRY_MANIFEST`, `NEXT_TEST_CONTINUE_ON_ERROR` to continue on error but do not retry on the known failed tests.
      # Do not set --timings flag
      - run: |
          docker run --rm -v $(pwd):/work mcr.microsoft.com/playwright:v1.28.1-focal /bin/bash -c "cd /work && ls && curl https://install-node.vercel.app/v${{ matrix.node }} | FORCE=1 bash && node -v && npm i -g pnpm@${PNPM_VERSION} && /work/next-dev --display-version && __INTERNAL_CUSTOM_TURBOPACK_BINARY=${NEXT_DEV_BIN} __INTERNAL_NEXT_DEV_TEST_TURBO_GLOB_MATCH=${NEXT_DEV_TEST_GLOB} NEXT_TEST_SKIP_RETRY_MANIFEST=${FAILED_TEST_LIST_PATH} NEXT_TEST_CONTINUE_ON_ERROR=TRUE NEXT_TEST_JOB=1 NEXT_TEST_MODE=dev xvfb-run node run-tests.js --type development -g ${{ matrix.group }}/4 >> /proc/1/fd/1"
        name: Run test/development
        # It is currently expected to fail some of next.js integration test, do not fail CI check.
        continue-on-error: true
        env:
          RECORD_REPLAY_METADATA_TEST_RUN_TITLE: testDev / Group ${{ matrix.group }}
          # marker to parse log output, do not delete / change.
          NEXT_INTEGRATION_TEST: true

  test_dev_e2e:
    # This job name is being used in github action to collect test results. Do not change it, or should update
    # ./.github/actions/next-integration-stat to match the new name.
    name: Next.js integration test (e2e/Development)
    runs-on: ubuntu-latest
    needs: [setup_nextjs]
    env:
      # Enabling backtrace will makes snapshot tests fail
      RUST_BACKTRACE: 0
      NEXT_TELEMETRY_DISABLED: 1
      # Path to the next-dev binary located in **docker container** image.
      NEXT_DEV_BIN: /work/next-dev
      FAILED_TEST_LIST_PATH: /work/integration-test-data/test-results/main/failed-test-path-list.json
      # Glob pattern to run specific tests with --turbo.
      NEXT_DEV_TEST_GLOB: "*"
      # pnpm version should match to what upstream next.js uses
      PNPM_VERSION: 7.24.3
    strategy:
      matrix:
        node: [16, 18]
        group: [1, 2, 3, 4, 5, 6, 7]

    steps:
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - run: |
          docker run --rm -v $(pwd):/work mcr.microsoft.com/playwright:v1.28.1-focal /bin/bash -c "cd /work && ls && curl https://install-node.vercel.app/v${{ matrix.node }} | FORCE=1 bash && node -v && npm i -g pnpm@${PNPM_VERSION} && __INTERNAL_CUSTOM_TURBOPACK_BINARY=${NEXT_DEV_BIN} __INTERNAL_NEXT_DEV_TEST_TURBO_GLOB_MATCH=${NEXT_DEV_TEST_GLOB} NEXT_TEST_SKIP_RETRY_MANIFEST=${FAILED_TEST_LIST_PATH} NEXT_TEST_CONTINUE_ON_ERROR=TRUE NEXT_TEST_JOB=1 NEXT_TEST_MODE=dev xvfb-run node run-tests.js --type e2e -g ${{ matrix.group }}/7 >> /proc/1/fd/1"
        name: Run test/e2e (dev)
        continue-on-error: true
        env:
          RECORD_REPLAY_METADATA_TEST_RUN_TITLE: testDevE2E / Group ${{ matrix.group }} / Node ${{ matrix.node }}
          NEXT_TEST_MODE: dev
          RECORD_REPLAY_TEST_METRICS: 1
          NEXT_INTEGRATION_TEST: true

  test_cna:
    # This job name is being used in github action to collect test results. Do not change it, or should update
    # ./.github/actions/next-integration-stat to match the new name.
    name: Next.js integration test (Create Next App) (No group)
    runs-on: ubuntu-latest
    needs: [setup_nextjs]
    env:
      # Enabling backtrace will makes snapshot tests fail
      RUST_BACKTRACE: 0
      NEXT_TELEMETRY_DISABLED: 1
      # Path to the next-dev binary located in **docker container** image.
      NEXT_DEV_BIN: /work/next-dev
      FAILED_TEST_LIST_PATH: /work/integration-test-data/test-results/main/failed-test-path-list.json
      # Glob pattern to run specific tests with --turbo.
      NEXT_DEV_TEST_GLOB: "*"
      # pnpm version should match to what upstream next.js uses
      PNPM_VERSION: 7.24.3

    steps:
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      # TODO: This test currently seems to load wasm/swc and does not load the next-dev binary.
      # Temporary disabled until figure out details.
      #- run: |
      #    docker run --rm -v $(pwd):/work mcr.microsoft.com/playwright:v1.28.1-focal /bin/bash -c "cd /work && curl -s https://install-node.vercel.app/v16 | FORCE=1 bash && npm i -g pnpm@${PNPM_VERSION} > /dev/null && __INTERNAL_CUSTOM_TURBOPACK_BINARY=${NEXT_DEV_BIN} __INTERNAL_NEXT_DEV_TEST_TURBO_GLOB_MATCH=${NEXT_DEV_TEST_GLOB} NEXT_TEST_SKIP_RETRY_MANIFEST=${FAILED_TEST_LIST_PATH} NEXT_TEST_CONTINUE_ON_ERROR=TRUE NEXT_TEST_JOB=1 NEXT_TEST_CNA=1 xvfb-run node run-tests.js test/integration/create-next-app/index.test.ts test/integration/create-next-app/templates.test.ts >> /proc/1/fd/1"
      #  name: Run test/e2e (create-next-app)
      #  continue-on-error: true
      #  env:
      #    RECORD_REPLAY_METADATA_TEST_RUN_TITLE: testDevE2E / Group ${{ matrix.group }} / Node ${{ matrix.node }}
      #    NEXT_TEST_MODE: dev
      #    RECORD_REPLAY_TEST_METRICS: 1
      #    NEXT_INTEGRATION_TEST: true

  test_integration:
    # This job name is being used in github action to collect test results. Do not change it, or should update
    # ./.github/actions/next-integration-stat to match the new name.
    name: Next.js integration test (integration)
    runs-on: ubuntu-latest
    needs: [setup_nextjs]
    env:
      # Enabling backtrace will makes snapshot tests fail
      RUST_BACKTRACE: 0
      NEXT_TELEMETRY_DISABLED: 1
      # Path to the next-dev binary located in **docker container** image.
      NEXT_DEV_BIN: /work/next-dev
      FAILED_TEST_LIST_PATH: /work/integration-test-data/test-results/main/failed-test-path-list.json
      # Glob pattern to run specific tests with --turbo.
      NEXT_DEV_TEST_GLOB: "*"
      # pnpm version should match to what upstream next.js uses
      PNPM_VERSION: 7.24.3
    strategy:
      fail-fast: false
      matrix:
        group:
          [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
          ]

    steps:
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - run: |
          docker run --rm -v $(pwd):/work mcr.microsoft.com/playwright:v1.28.1-focal /bin/bash -c "cd /work && ls && curl https://install-node.vercel.app/v16 | FORCE=1 bash && node -v && npm i -g pnpm@${PNPM_VERSION} && __INTERNAL_CUSTOM_TURBOPACK_BINARY=${NEXT_DEV_BIN} __INTERNAL_NEXT_DEV_TEST_TURBO_GLOB_MATCH=${NEXT_DEV_TEST_GLOB} NEXT_TEST_SKIP_RETRY_MANIFEST=${FAILED_TEST_LIST_PATH} NEXT_TEST_CONTINUE_ON_ERROR=TRUE NEXT_TEST_JOB=1 xvfb-run node run-tests.js -g ${{ matrix.group }}/25 >> /proc/1/fd/1"
        name: Test Integration
        continue-on-error: true
        env:
          RECORD_REPLAY_METADATA_TEST_RUN_TITLE: testIntegration / Group ${{ matrix.group }}
          NEXT_INTEGRATION_TEST: true

  # Collect integration test results from execute_tests,
  # Store it as github artifact for next step to consume.
  collect_nextjs_integration_stat:
    needs: [test_dev, test_dev_e2e, test_cna, test_integration]
    name: Next.js integration test status report
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Collect integration test stat
        uses: ./.github/actions/next-integration-stat
        with:
          diff_base: ${{ inputs.diff_base }}
        env:
          NEXT_TURBO_FORCE_SLACK_UPDATE: "${{ inputs.force_post_to_slack }}"

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            nextjs-test-results.json
            failed-test-path-list.json
            slack-payload.json
