# A workflow supposed to run when there is a new changes committed in default branch.
name: On Default Branch Update
on:
  push:
    branches:
      - main

jobs:
  # Trigger actual next.js integration tests.
  next_js_integration:
    name: Execute Next.js integration workflow
    permissions:
      pull-requests: write
    uses: ./.github/workflows/nextjs-integration-test.yml

  # Upload test results to branch.
  upload_test_results:
    name: Upload test results
    needs: [next_js_integration]
    uses: ./.github/workflows/upload-nextjs-integration-test-results.yml
    with:
      is_main_branch: true
