# A workflow supposed to run when there is a new release of Next.js.
# This relies on next.js upstream's `repository_dispatch` workflow.
name: Next.js Release Publish

on:
  repository_dispatch:
    # This is the event type defined by next.js upstream's `repository_dispatch` workflow dispatches.
    types: [nextjs-release-published]
  workflow_dispatch:
    inputs:
      version:
        description: Next.js version
        type: string
      force_post_to_slack:
        description: Post test results to Slack
        type: boolean

jobs:
  # Debug purpose, write down release version.
  check-release-tag:
    name: Check latest release
    runs-on: ubuntu-latest
    steps:
      - name: Print release tag
        run: echo "Found a new release via ${{ github.event_name }} -- ${{ inputs.version || github.event.client_payload.version }}"

  # Trigger actual next.js integration tests.
  next_js_integration:
    name: Execute Next.js integration workflow
    permissions:
      pull-requests: write
    uses: ./.github/workflows/nextjs-integration-test.yml
    with:
      force_post_to_slack: ${{ inputs.force_post_to_slack || false }}
      version: ${{ inputs.version || github.event.client_payload.version }}
      diff_base: "release"

  # Upload test results to branch.
  upload_test_results:
    name: Upload test results
    # Don't upload results when this workflow is run manually via workflow_dispatch
    if: ${{ github.event_name != 'workflow_dispatch' }}
    needs: [next_js_integration]
    uses: ./.github/workflows/upload-nextjs-integration-test-results.yml
    with:
      is_main_branch: false

  post_to_slack:
    needs: [next_js_integration]
    name: Post results to Slack
    runs-on: ubuntu-latest
    steps:
      - name: Download summary.md artifact
        uses: actions/download-artifact@v3
        with:
          name: test-results
      - name: Check if summary file was generated
        id: summary_check
        run: |
          if stat slack-payload.json; then
            echo "should_continue=true" >> $GITHUB_OUTPUT
          else
            echo "should_continue=false" >> $GITHUB_OUTPUT
          fi
      - name: Send test data to Slack workflow
        if: steps.summary_check.outputs.should_continue == 'true'
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload-file-path: "./slack-payload.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.NEXT_TURBO_INTEGRATION_SLACK_WEBHOOK_URL }}
