name: CLI Unit Tests
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: 'echo "No unit test run required"'
