name: Turborepo Integration tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, edited, synchronize]
    paths-ignore:
      - "**.md"
      - "**.mdx"
      - "docs/**"
      - "examples/**"

jobs:
  test:
    timeout-minutes: 30
    runs-on: ${{ matrix.os.runner }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu
            runner: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-debug-turborepo
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          target: ${{ matrix.os.name }}

      - name: Cache Prysk
        id: cache-prysk
        uses: actions/cache@v3
        with:
          path: cli/.cram_env
          key: prysk-venv-${{ matrix.os.name }}

      - name: Integration Tests
        run: pnpm -- turbo run integration-tests --filter=cli
