name: Turborepo E2E tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, edited, synchronize]
    paths-ignore:
      - "**.md"
      - "**.mdx"
      - "docs/**"
      - "examples/**"

jobs:
  test:
    timeout-minutes: 30
    runs-on: ${{ matrix.os.runner }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu
            runner: ubuntu-latest
          - name: macos
            runner: macos-latest
          - name: windows
            runner: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-debug-turborepo
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          target: ${{ matrix.os.name }}

      - name: E2E Tests
        # Turbo has already been built in previous step, no need to rebuild
        run: pnpm -- turbo-prebuilt run e2e-prebuilt --filter=cli

  cleanup:
    name: Cleanup
    needs: [test]
    if: always()
    uses: ./.github/workflows/pr-clean-caches.yml
    secrets: inherit
