name: JS Package Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, edited, synchronize]
    paths-ignore:
      - "**.md"
      - "**.mdx"
      - "docs/**"
      - "examples/**"

jobs:
  test:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true

    steps:
      - uses: actions/checkout@v3
      - name: checkout
        # We want to fetch all of the commits in PR and the commit it's based on
        # If this isn't a PR, then this is a push and we check against the previous commit
        run: |
          pr_commits=${{ github.event.pull_request.commits }}
          if [[ -n "$pr_commits" ]]; then
            git fetch --no-tags --prune --progress --depth="$(( pr_commits + 1 ))" origin +${{ github.event.pull_request.base.sha }}:${{ github.ref }}
            git checkout ${{ github.ref }} --force
          else
            git fetch --no-tags --prune --progress --depth=2
          fi
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-go
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      # Note this runs nothing on push since event is push and not pull_request and ...[] matches nothing?
      # For push we should just do ..[HEAD^]
      - if: ${{ github.event.pull_request }}
        run: |
          pnpm -- turbo run test  --filter=...[${{ github.event.pull_request.base.sha }}] --filter=!cli --color
      - if: ${{ github.event.push }}
        run: |
          pnpm -- turbo run test  --filter=...[HEAD^1] --filter=!cli --color
