name: JS Package Tests
 create: cache
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: await response and commit

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  test:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-go
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - run: pnpm -- turbo run test --filter=!cli --color
