name: Publish docs

on:
  push:
    branches: [main]

jobs:
  build_docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-rust

      - run: cargo doc --no-deps

      - uses: actions/upload-artifact@v3
        with:
          name: docs_rs
          path: ./target/doc/

  commit_docs:
    name: Commit docs
    needs: build_docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - uses: actions/download-artifact@v3
        with:
          name: docs_rs
          path: ./target/doc
      - run: ls -a
      - run: rm -rf ./docs/docs.rs
      - run: mkdir docs || true # || true to make sure exit code is 0 even if dir exists
      - run: cp -r ./target/doc ./docs/docs.rs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update docs (${{ github.sha }})
