name: Test

on:
  push:
    branches: [main, staging]
  pull_request:
    types: [synchronize, opened, reopened, edited]
    branches: [main, staging]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu-latest
            nextest: linux
          - name: macos-latest
            nextest: mac
            # Using the `windows-2019` runner instead of latest(`windows-2022`)
            # because the build was last known working on that version of runner and
            # `prebuild` fails to find the 2022 Visual Studio install because
            # it's internally using an old version of `node-gyp`, see
            # https://github.com/prebuild/prebuild/issues/286
            #
            # ref: https://github.com/MadLittleMods/node-usb-detection/blob/ae2fc13e9ad6a09927f4516358dea4c4ca2ceb92/.github/workflows/ci.yml#L18
            version: 2019
          - name: windows-2019
            nextest: windows-tar
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No test run required"'
