name: Smoke Test Published

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

jobs:
  test_matrix:
    name: "Test local turbo@${{ matrix.localVersion }} with global turbo@${{ matrix.globalVersion }} (${{ matrix.packageManager }}, ${{ matrix.test }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: ["local", "global", "both"]
        packageManager: ["yarn", "pnpm", "npm"]
        localVersion: ["latest", "canary"]
        globalVersion: ["latest", "canary"]
    steps:
      - name: Install ts-node
        run: npm install ts-node --global
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        if: ${{ matrix.packageManager == 'pnpm' }}
        with:
          version: 7.12.1
      - name: Setup yarn
        if: ${{ matrix.packageManager == 'yarn' }}
        run: npm install -g yarn
      - name: Checkout test file
        uses: Bhacaz/checkout-files@v2
        with:
          files: scripts/smoke-published.ts
      - name: Run Test
        run: ts-node scripts/smoke-published.ts ${{ matrix.test }} ${{ matrix.packageManager }} ${{ matrix.localVersion }} ${{ matrix.globalVersion }}
