[package]
name = "sync-workspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
indexmap = "1.7.0"
indoc = "2.0.1"
toml = "0.7.2"
